name: pubmed tools evals
description: |
  Evaluations for multiple pubmed MCPs

coders:
  goose: {}

models:
  claude-4-sonnet:
    provider: anthropic
    name: claude-sonnet-4-20250514

servers:
  artl:
    name: artl
    command: uvx
    args: [artl-mcp]
  simple-pubmed:
    name: pubmed
    command: uvx
    args: [mcp-simple-pubmed]
    env:
      PUBMED_EMAIL: ctparker@lbl.gov
  biomcp:
    name: biomcp
    command: uv
    args: ["run", "--with", "biomcp-python", "biomcp", "run"]
  pubmed-mcp:
    name: pubmed-mcp
    command: uv
    args: ["run", "--with", "git+https://github.com/chrismannina/pubmed-mcp@main", "-m", "src.main"]
    env:
      PUBMED_API_KEY: "01eec0a16472164c6d69163bd28368311808"

server_combinations:
  - [artl]
  - [simple-pubmed]
  - [biomcp]
  - [pubmed-mcp]

cases:
- name: NBK1256
  group: "Table / Figure / Figure Legend extraction"
  metrics:
  - CorrectnessMetric
  input: "What is the last row of Table 2 in NBK1256?"
  expected_output: "Cone-rod dystrophy,70%,Loss of central vision & color vision\nAbnormal fundoscopic exam"
  threshold: 0.9
