name: pubmed tools evals
description: |
  Evaluations for multiple pubmed MCPs

coders:
  goose: {}

models:
  claude-4-sonnet:
    provider: anthropic
    name: claude-sonnet-4-20250514

servers:
  artl:
    name: artl
    command: uvx
    args: [artl-mcp]
  simple-pubmed:
    name: pubmed
    command: uvx
    args: [mcp-simple-pubmed]
    env:
      PUBMED_EMAIL: ctparker@lbl.gov
  ols:
    name: ols
    command: uvx
    args: [mcp-ols]

server_combinations:
  - [artl]
  - [simple-pubmed]
#  - [ols]

cases:
- name: PMID_28027860_Full_Text
  group: Text extraction
  metrics:
  - CorrectnessMetric
  input: 'What is the first sentence of section 2 in PMID: 28027860?'
  expected_output: "Even though many of NFLE\u2019s core features have been clarified\
    \ in\nthe last two decades, some critical issues remain controversial."
  threshold: 0.9

- name: PMID_28027860_Title
  group: Metadata
  metrics:
  - CorrectnessMetric
  input: What is the title of PMID:28027860?
  expected_output: 'From nocturnal frontal lobe epilepsy to Sleep-Related Hypermotor
    Epilepsy: A 35-year diagnostic challenge'
  threshold: 0.9

- name: PMID_28027860_Table
  group: Summarization
  metrics:
  - CorrectnessMetric
  input: According to PMID:28027860, what are the three levels of certainty for SHE
  expected_output: witnessed; video-documented; Video-EEG documented
  threshold: 0.9

- name: PMID_28027860_References
  group: Text extraction
  metrics:
  - CorrectnessMetric
  input: Find the citation in the paper PMID:28027860 for the claim "The clinical
    spectrum of NFLS comprises distinct paroxysmal sleep-related attacks of variable
    duration and complexity". What is the title of cited paper?
  expected_output: The concept of paroxysmal nocturnal dystonia
  threshold: 0.9

- name: 10.1016_j.seizure.2016.11.023_Full_Text
  group: Text extraction
  metrics:
  - CorrectnessMetric
  input: What is the last paragraph from 10.1016/j.seizure.2016.11.023, before the conflict of interest
  expected_output: 'SHE diagnosis is primarily based on the clinical history...'
  threshold: 0.9

- name: NBK1256
  group: Table / Figure / Figure Legend extraction
  metrics:
  - CorrectnessMetric
  input: What are the last two rows of Table 2 in NBK1256?
  expected_output: "Behavior disorder/\nPsychosis        10% ..."
  threshold: 0.9

- name: PMID_40307501_Figure_Legend
  group: Table / Figure / Figure Legend extraction
  metrics:
  - CorrectnessMetric
  input: What is the first sentence of figure 1 legend from PMID 40307501?
  expected_output: Proposed system for bio-accelerated weathering...
  threshold: 0.9

- name: 10.1371_journal.pone.0000217_Full_Text_A
  group: Text extraction
  metrics:
  - CorrectnessMetric
  input: Convert the PDF for DOI 10.1371/journal.pone.0000217...
  expected_output: However, phenotypic complexity remains an inherently abstract metric.
  threshold: 0.9

- name: 10.1371_journal.pone.0000217_Full_Text_B
  group: Supplementary material
  metrics:
  - CorrectnessMetric
  input: How many appendices are in 10.1371/journal.pone.0000217?
  expected_output: '3'
  threshold: 0.9

- name: 10.1038_nature12373_Full_Text
  group: Text extraction
  metrics:
  - CorrectnessMetric
  input: Get the full text content for DOI 10.1038/nature12373...
  expected_output: Nanodiamonds and Au NPs were introduced...
  threshold: 0.9

- name: 10.1038_nature12373_Supplementary_Material_A
  group: Supplementary material
  metrics:
  - CorrectnessMetric
  input: What supplementary files are available for PMC4221854?
  expected_output: NIHMS636072-supplement-supplemental_info.pdf
  threshold: 0.9

- name: 10.1038_nature12373_Supplementary_Material_B
  group: Supplementary material
  metrics:
  - CorrectnessMetric
  input: What is the figure legend for Figure S3
  expected_output: 'Schematic Setup...'
  threshold: 0.9

- name: PMC2824148_Full_Text
  group: Text extraction
  metrics:
  - CorrectnessMetric
  input: What is the last sentence of PMC2824148 before the Acknowledgements?
  expected_output: As far as the future work is concerned...
  threshold: 0.9

- name: PMC2824148_Metadata
  group: Metadata
  metrics:
  - CorrectnessMetric
  input: 'What is the DOI for the final published version of '
  expected_output: 10.1142/S0219720006001977
  threshold: 0.9

- name: 10.1038_s41564-022-01094-z_Full_Text_A
  group: Text extraction
  metrics:
  - CorrectnessMetric
  input: What are the main section headers in PMC8975739?
  expected_output: 'Abstract ... References ...'
  threshold: 0.9

- name: 10.1038_s41564-022-01094-z_Full_Text_B
  group: Text extraction
  metrics:
  - CorrectnessMetric
  input: 'What is the longest section in PMID:35365791?'
  expected_output: Methods
  threshold: 0.9

- name: PMID_12089011_Full_Text
  group: Table / Figure / Figure Legend extraction
  metrics:
  - CorrectnessMetric
  input: 'What is the first footnote of Table 3 in PMID:12089011?'
  expected_output: a Grouping at 89% similarity
  threshold: 0.9

- name: PMC5152751_Metadata
  group: Metadata
  metrics:
  - CorrectnessMetric
  input: Which publisher published PMC5152751?
  expected_output: Nature
  threshold: 0.9

- name: PMC3368421_nan
  group: Table / Figure / Figure Legend extraction
  metrics:
  - CorrectnessMetric
  input: What is the MIGS-22 property from Table 1?
  expected_output: Oxygen requirement aerobe
  threshold: 0.9

- name: PMID_32198168_nan
  group: Text extraction
  metrics:
  - CorrectnessMetric
  input: 'What does the data management section state in PMID:32198168?'
  expected_output: Clinical data were collected...
  threshold: 0.9

- name: PMC3815380_PDF
  group: Metadata
  metrics:
  - CorrectnessMetric
  input: Who was the REVIEWS AND SPECIAL ISSUE EDITOR for PMC3815380?
  expected_output: "Juan L. Ramos..."
  threshold: 0.9

- name: PMC117972_Full_Text
  group: Text extraction
  metrics:
  - CorrectnessMetric
  input: What is the first sentence of the Microarray Analysis section in PMC117972?
  expected_output: 'A global representation of the changes...'
  threshold: 0.9

- name: PMC4831113_Full_Text
  group: Text extraction
  metrics:
  - CorrectnessMetric
  input: Show the Conclusions section of PMC4831113.
  expected_output: 'On the basis of phenotypic, phylogenetic and genomic analyses...'
  threshold: 0.9

- name: PMC4831113_Retraction
  group: Publication status
  metrics:
  - CorrectnessMetric
  input: Is PMC4831113 retracted?
  expected_output: 'Yes'
  threshold: 0.9

# Per convo with Charles, Justin, Mark: this test case is kind of tricky and it seems
# like an extremely difficult case that even a good LLM + MCP might not pass. We've
# made some edits to give the LLM + MCP a fair chance
- name: PMC8086273_Retraction
  group: Summarization
  metrics:
  - CorrectnessMetric
  input: Based on PMID 33926573 do microbes from alkaline sulphidic tailings show oxidative stresses? Is this finding from this paper reliable?
  expected_output: 'The paper says no, microbes from alkaline sulphidic tailings do not show oxidative stresses, but it is retracted so the results should not be trusted.'
  threshold: 0.9
