name: pubmed tools evals
description: |
  Evaluations for multiple pubmed MCPs


coders:
  goose: {}

models:
  claude-sonnet:
    provider: anthropic
    name: claude-sonnet-4-20250514

# Refer to metacoder/src/mcps/registry/scilit.yaml for the list of available MCPs.
servers:
  artl:
    name: artl
    command: uvx
    args: [artl-mcp]
  simple-pubmed:
    name: pubmed
    command: uvx
    args: [mcp-simple-pubmed]
    env:
      PUBMED_EMAIL: ctparker@lbl.gov
  ols:
    name: ols
    command: uvx
    args: [mcp-ols]

server_combinations:
#  - [artl, simple-pubmed, ols]
  - [artl]
  - [simple-pubmed]
#  - [ols]

cases:
- name: PMID_28027860_Full_Text
  group: Text extraction
  metrics:
  - CorrectnessMetric
  input: 'What is the first sentence of section 2 in PMID: 28027860?'
  expected_output: "Even though many of NFLE\u2019s core features have been clarified\
    \ in\nthe last two decades, some critical issues remain controversial."
  threshold: 0.9

# Per convo with Charles, Justin, Mark: this test case is kind of tricky and it seems
# like an extremely difficult case that even a good LLM + MCP might not pass. We've
# made some edits to give the LLM + MCP a fair chance
- name: PMC8086273_Retraction
  group: Summarization
  metrics:
  - CorrectnessMetric
  input: Based on PMID 33926573 do microbes from alkaline sulphidic tailings show oxidative stresses?
  expected_output: 'The paper says No but it is retracted so the results should not be trusted.'
  threshold: 0.9
